services:

  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx

  nginx:
    build:
      context: .
      dockerfile: DockerfileFE
    image: mangablade-frontend:latest
    depends_on:
      - spring-boot

  spring-boot:
    build:
      context: .
      dockerfile: DockerfileBE
    image: mangablade-backend:latest
    environment:
      DB_URL: jdbc:mysql://mysql:3306/MangaBlade?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - mysql
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1
    container_name: mangablade-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  mysql:
    image: mysql:latest
    container_name: mangablade-mysql
    environment:
      MYSQL_DATABASE: MangaBlade
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
