spring:
  config:
    import:
      - "optional:file:./backend/.env[.properties]"

  application:
    name: mangablade-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/MangaBlade?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  app:
    otruyen:
      import-cron: "*/10 * * * * *"
